# Molly Moran
## Week 10 - 10/28/2025
### Python numpy Intro


**What is NumPy, and why?**
what


**What is NumPy, and why?**

What:
- NumPy is a Python library.
- NumPy is used for working with arrays.
- NumPy i short for "Numerical Python".

**Why use NumPy**
- Arrays are very frequently used in data science, where speed and resources are very important.
- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array of objects that is up to 50x faster than tradtional Python lists.
- The array object in NumPy is called 'ndarray'.
- NumPy is written partailly in Python, but most of the parts that require fast computation are writtenin C or C++
- This Behavior is called locallity of refrence in computer science.
-

In [1]:
import numpy as np

In [3]:
np.__version__

'1.18.5'

In [4]:
import random

lst = random.choices(range(5,11),k=10)
lst

[7, 7, 8, 7, 9, 5, 8, 6, 10, 8]

In [5]:
arr = np.array(lst)
arr

array([ 7,  7,  8,  7,  9,  5,  8,  6, 10,  8])

In [6]:
type(arr)

numpy.ndarray

In [7]:
'''
A dimesnion in arrays is one level of array depth (nested arrays).
nested array: are arrays that have arrays as their elements.
'''

# 0-D Array: Scholars are the elements in a 0-D array
arr_0 = np.array(10)
arr_0

array(10)

In [9]:
arr_0.ndim

0

In [10]:
arr_0.shape

()

In [12]:
# 1-D Arrays: An array that has 0-D arrays as its elements
arr_1 = np.array(lst)
arr_1

array([ 7,  7,  8,  7,  9,  5,  8,  6, 10,  8])

In [13]:
arr_1.ndim

1

In [14]:
arr_1.shape

(10,)

In [15]:
# 2-D Array: An array that has 1-D arrays as its elements 
arr_2 =np.array([arr_1, arr_1 * 2])
arr_2

array([[ 7,  7,  8,  7,  9,  5,  8,  6, 10,  8],
       [14, 14, 16, 14, 18, 10, 16, 12, 20, 16]])

In [16]:
arr_2.ndim

2

In [17]:
arr_2.shape

(2, 10)

In [20]:
#3-D array: An array that has 2-D arraay(matracies) as its elements
arr_3 = np.array([arr_2 ,arr_2 * 3])
arr_3

array([[[ 7,  7,  8,  7,  9,  5,  8,  6, 10,  8],
        [14, 14, 16, 14, 18, 10, 16, 12, 20, 16]],

       [[21, 21, 24, 21, 27, 15, 24, 18, 30, 24],
        [42, 42, 48, 42, 54, 30, 48, 36, 60, 48]]])

In [21]:
arr_3.ndim

3

In [22]:
arr_3.shape

(2, 2, 10)

In [26]:
# create 4-D
arr_4 = np.array(lst,ndmin=4)
arr_4

array([[[[ 7,  7,  8,  7,  9,  5,  8,  6, 10,  8]]]])

In [27]:
arr_4.shape

(1, 1, 1, 10)

In [28]:
# create 5-D
arr_5 = np.array(lst,ndmin=5)
arr_5

array([[[[[ 7,  7,  8,  7,  9,  5,  8,  6, 10,  8]]]]])

In [30]:
# Array Indexing
arr_1

array([ 7,  7,  8,  7,  9,  5,  8,  6, 10,  8])

In [31]:
arr_1[0]

7

In [34]:
arr_1[-1]

8

In [35]:
arr_1[3]

7

In [36]:
# 2-D array indexing
arr_2

array([[ 7,  7,  8,  7,  9,  5,  8,  6, 10,  8],
       [14, 14, 16, 14, 18, 10, 16, 12, 20, 16]])

In [37]:
arr_2[0]

array([ 7,  7,  8,  7,  9,  5,  8,  6, 10,  8])

In [39]:
arr_2[0,-1]

8

In [40]:
arr_2.shape

(2, 10)

In [41]:
arr_2[1,-2]

20

In [42]:
arr_2[1]

array([14, 14, 16, 14, 18, 10, 16, 12, 20, 16])

In [43]:
# 3-D array
arr_3

array([[[ 7,  7,  8,  7,  9,  5,  8,  6, 10,  8],
        [14, 14, 16, 14, 18, 10, 16, 12, 20, 16]],

       [[21, 21, 24, 21, 27, 15, 24, 18, 30, 24],
        [42, 42, 48, 42, 54, 30, 48, 36, 60, 48]]])

In [45]:
arr_3.shape

(2, 2, 10)

In [46]:
arr_3[1]

array([[21, 21, 24, 21, 27, 15, 24, 18, 30, 24],
       [42, 42, 48, 42, 54, 30, 48, 36, 60, 48]])

In [47]:
arr_3[1,0]

array([21, 21, 24, 21, 27, 15, 24, 18, 30, 24])

In [48]:
arr_3[1,1]

array([42, 42, 48, 42, 54, 30, 48, 36, 60, 48])

In [50]:
arr_3[1,0,3]

21

In [51]:
# slicing np arrays
# [start:end:step], default start=0, end= length of the array, step=1
# sLsicing 1-D array
arr_1

array([ 7,  7,  8,  7,  9,  5,  8,  6, 10,  8])

In [53]:
arr_1[-3:]

array([ 6, 10,  8])

In [54]:
arr_1[:5]

array([7, 7, 8, 7, 9])

In [56]:
# Slicing 2-D arrays
arr_2

array([[ 7,  7,  8,  7,  9,  5,  8,  6, 10,  8],
       [14, 14, 16, 14, 18, 10, 16, 12, 20, 16]])

In [57]:
arr_2.shape

(2, 10)

In [58]:
arr_2[0:-3:]

array([], shape=(0, 10), dtype=int32)

In [62]:
arr_2[1,:4]

array([14, 14, 16, 14])

In [65]:
arr_2[:,-2:]

array([[10,  8],
       [20, 16]])

In [66]:
arr_2[:,0]

array([ 7, 14])

In [67]:
# slicing 3-D array
arr_3

array([[[ 7,  7,  8,  7,  9,  5,  8,  6, 10,  8],
        [14, 14, 16, 14, 18, 10, 16, 12, 20, 16]],

       [[21, 21, 24, 21, 27, 15, 24, 18, 30, 24],
        [42, 42, 48, 42, 54, 30, 48, 36, 60, 48]]])

In [68]:
arr_3.shape

(2, 2, 10)

In [69]:
arr_3[0,:,:2]

array([[ 7,  7],
       [14, 14]])

In [70]:
arr_3[:,:,:2]

array([[[ 7,  7],
        [14, 14]],

       [[21, 21],
        [42, 42]]])

In [73]:
arr_3[1:,:,-2:]

array([[[30, 24],
        [60, 48]]])

In [78]:
arr_3[1:,:,-2:11]

array([[[30, 24],
        [60, 48]]])

In [76]:
arr_3[1,1,5:11]

array([30, 48, 36, 60, 48])