# Molly Moran
## Week10 10/30/2025
### Python Numpy - Data Types

In [1]:
'''
Data types in NumPy
NumPy has some extra data types, and refer to data types with one character,
like I for integers, u for unassigned inregers ect.

Checking the Data Type of an Array 
The NumPy array object has a property called 'dtype' that returns the data type of the array
'''

"\nData types in NumPy\nNumPy has some extra data types, and refer to data types with one character,\nlike I for integers, u for unassigned inregers ect.\n\nChecking the Data Type of an Array \nThe NumPy array object has a property called 'dtype' that returns the data type of the array\n"

In [2]:
import numpy as np

In [4]:
arr = np.array(range(5,15))
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr.ndim

1

In [6]:
arr.shape

(10,)

In [7]:
import random
lst1 = random.choices(range(1,20), k=5)
lst2 = random.choices(range(50,70), k=5)

arr2 = np.array([lst1, lst2])
arr2

array([[13,  2,  8,  8,  6],
       [66, 59, 62, 57, 66]])

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(2, 5)

In [10]:
arr2.dtype

dtype('int32')

In [11]:
arr = np.array(['Orange', 'Apple', 'Cherry', 'Grape'])
arr

array(['Orange', 'Apple', 'Cherry', 'Grape'], dtype='<U6')

In [12]:
arr.dtype

dtype('<U6')

In [16]:
lst = ['Orange', 'Apple', 'Cherry', 'Grape', 1,2,3,4,5,2.5,4.5,3.8,True,False,[1,2,3,4,5],(1,2,3,4)]
arr = np.array(lst)
arr

array(['Orange', 'Apple', 'Cherry', 'Grape', 1, 2, 3, 4, 5, 2.5, 4.5, 3.8,
       True, False, list([1, 2, 3, 4, 5]), (1, 2, 3, 4)], dtype=object)

In [17]:
arr.dtype

dtype('O')

In [19]:
type(lst)

list

In [20]:
len(arr)

16

In [21]:
# converting Data Type on Exsisitng Arrays
# astype()
arr = np.array([1,2,3,4,5], dtype='S')
arr

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [22]:
arr.dtype

dtype('S1')

In [26]:
arr = np.array([1,2,3,4,5], dtype='i4')
arr

array([1, 2, 3, 4, 5])

In [27]:
arr.dtype

dtype('int32')

In [29]:
arr = np.array([1,2,3,4,5], dtype='i8')
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [30]:
arr = np.array(['1', '2', '3', '4'], dtype='i')
arr

array([1, 2, 3, 4], dtype=int32)

In [31]:
# convert an array after it is created
scores = [random.random() * 100 for _ in range(10)]
scores

[49.860114952913506,
 62.01534557763318,
 66.42560662852114,
 10.737922188232607,
 93.12800403815817,
 78.74149192567675,
 55.105500284632434,
 81.96515856850564,
 15.47454909239544,
 27.879298853797074]

In [33]:
arr = np.array(scores)
arr

array([49.86011495, 62.01534558, 66.42560663, 10.73792219, 93.12800404,
       78.74149193, 55.10550028, 81.96515857, 15.47454909, 27.87929885])

In [34]:
arr.dtype

dtype('float64')

In [35]:
arr_int = arr.astype('i8')
arr_int

array([49, 62, 66, 10, 93, 78, 55, 81, 15, 27], dtype=int64)

In [36]:
arr_b = arr.astype(bool)
arr_b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [37]:
# NumPy Array Copy as View
# the copy is a new array, and the view is just a view of the original array
# view(), copy(), assignment = 
arr = np.array(range(1,11))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr_assign = arr
arr_assign

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr[:2] = [55,55]
arr

array([55, 55,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr_assign

array([55, 55,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr_v = arr.view()
arr

array([55, 55,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr_v

array([55, 55,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[-1] = 100
arr

array([ 55,  55,   3,   4,   5,   6,   7,   8,   9, 100])

In [45]:
arr_v

array([ 55,  55,   3,   4,   5,   6,   7,   8,   9, 100])

In [46]:
arr_c = arr.copy()
arr_c

array([ 55,  55,   3,   4,   5,   6,   7,   8,   9, 100])

In [47]:
arr[-2:] = [0,0]
arr

array([55, 55,  3,  4,  5,  6,  7,  8,  0,  0])

In [48]:
arr_c

array([ 55,  55,   3,   4,   5,   6,   7,   8,   9, 100])

In [49]:
arr_v

array([55, 55,  3,  4,  5,  6,  7,  8,  0,  0])

In [50]:
arr_assign

array([55, 55,  3,  4,  5,  6,  7,  8,  0,  0])

In [54]:
arr.base

In [52]:
print(arr.base)

None


In [53]:
print(arr_assign.base)

None


In [55]:
print(arr_v.base)

[55 55  3  4  5  6  7  8  0  0]


In [56]:
print(arr_c.base)

None


In [57]:
'''
np.vstack: To stack arrays along vertical axis.
np.hstack: To stack arrays along horizontal axis.
'''

a = np.array([[1,2],[3,4]])
b = np.array([[5,6], [7,8]])

In [58]:
a.shape

(2, 2)

In [59]:
b.shape

(2, 2)

In [60]:
arr_vs = np.vstack((a,b))
arr_vs

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [61]:
arr_vs.shape

(4, 2)

In [64]:
arr_hs = np.hstack((a,b))
arr_hs

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [65]:
arr_hs.shape

(2, 4)

In [66]:
# Reading data from files
f = open("data.txt", "w")
f.write("1, 2, 3\n")
f.write("4, 5, 6")
f.close()

In [67]:
f = open('data.txt', 'r')
print(f.read())

1, 2, 3
4, 5, 6


In [69]:
# Using np.genfromtxt
arr2 = np.genfromtxt('data.txt', dtype=None, delimiter=',')
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
arr2.shape

(2, 3)

In [71]:
# Using np.loadtxt
arr2 = np.loadtxt('data.txt', dtype='<U6', delimiter=',')
arr2

array([['1', ' 2', ' 3'],
       ['4', ' 5', ' 6']], dtype='<U6')