# Molly Moran
## Week 10 10/30/2025
### Python numpy creating, processing, transporting arrays


In [1]:
import numpy as np
arr2 = np.array([range(1,6), range(6,11)])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [2]:
arr2.shape

(2, 5)

In [3]:
arr2.dtype

dtype('int32')

In [4]:
# Return a new array of given shape and type, filled with zeros.
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
arr = np.zeros((5,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
arr = np.empty((3,5,4)) # it creates a new NumPy array with random values.
arr

array([[[6.90777145e-312, 6.90771238e-312, 3.37208071e+175,
         9.47791318e+170],
        [1.00221861e-310, 5.89222505e-222, 1.73712675e-260,
         1.79192632e-312],
        [1.00813461e-109, 6.33825300e+030, 8.40609137e-284,
         1.76380243e+241],
        [9.70499019e-308, 3.06947261e-314, 1.29836157e-288,
         4.04456750e+242],
        [1.33091396e-109, 9.80591156e+252, 3.40264938e-309,
         1.33360290e+241]],

       [[3.30908559e+257, 2.07226689e+243, 1.81685280e-310,
         1.48100916e-304],
        [6.79907823e-308, 1.33360292e+241, 5.13098582e-311,
         1.53446210e-253],
        [2.64089007e-313, 1.92950754e+222, 1.67433458e+243,
         1.78935720e+161],
        [7.84814656e-311, 9.10016855e+276, 2.14815034e-308,
         1.16968885e+214],
        [9.30194405e+242, 9.11716200e+242, 9.19596694e+170,
         8.87696988e+247]],

       [[4.09509621e-308, 1.33360297e+241, 8.93360228e-311,
         7.96738272e-220],
        [1.38874678e-312, 4.54923304e-3

In [11]:
arr = np.empty((3,3)) # it creates a new numpy with random values
arr

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 6.067e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

In [13]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.arange(1,25,5)
arr

array([ 1,  6, 11, 16, 21])

In [15]:
#reshape
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
len(arr)

12

In [17]:
arr2 = arr.reshape((3,4)) # reshape 1-D to 2-D
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
arr2 = arr.reshape((4,3)) # reshape 1-D to 2-D
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
arr2 = arr.reshape((6,2)) #reshape 1-D to 2-D
arr2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [20]:
arr[:2] = [0,0]

In [21]:
arr

array([ 0,  0,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
arr2

array([[ 0,  0],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [23]:
len(arr)

12

In [24]:
arr.reshape((5,3))

ValueError: cannot reshape array of size 12 into shape (5,3)