# Molly Moran
## Week 11 - 11/4/2025
### Python Numpy Reshape, transpose, T., Swapaxis

In [5]:
import numpy as np
arr = np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
arr = np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
arr.base

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
arr = np.arange(1,13).reshape(2,3,2)
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [9]:
arr.ndim

3

In [11]:
arr = np.arange(1,13).reshape(3,2,2)
arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [12]:
arr.shape

(3, 2, 2)

In [14]:
arr = np.arange(1,13).reshape(2,-1,3) # use -1 for unknown dimension
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [15]:
arr.shape

(2, 2, 3)

In [16]:
# Iterating Arrays
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
for n in arr:
    print(n)

0
1
2
3
4
5
6
7
8
9


In [18]:
arr2 = arr.reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
for n in arr2:
    print(n)

[0 1 2 3 4]
[5 6 7 8 9]


In [20]:
for n in arr2:
    for num in n:
        print(num)

0
1
2
3
4
5
6
7
8
9


In [27]:
for n in np.arange(12).reshape(2,2,3):
    for n1 in n:
        for n2 in n1:
            print(n2)

0
1
2
3
4
5
6
7
8
9
10
11


In [31]:
# nditer iterates on each scalar element in the np array
arr = np.arange(24).reshape(2,2,3,2)

for n in np.nditer(arr):
    print(n)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [33]:
# Enumerate Iteration Using ndemerate(), return element and index of the element
for n in np.ndenumerate(arr):
    print(n)

((0, 0, 0, 0), 0)
((0, 0, 0, 1), 1)
((0, 0, 1, 0), 2)
((0, 0, 1, 1), 3)
((0, 0, 2, 0), 4)
((0, 0, 2, 1), 5)
((0, 1, 0, 0), 6)
((0, 1, 0, 1), 7)
((0, 1, 1, 0), 8)
((0, 1, 1, 1), 9)
((0, 1, 2, 0), 10)
((0, 1, 2, 1), 11)
((1, 0, 0, 0), 12)
((1, 0, 0, 1), 13)
((1, 0, 1, 0), 14)
((1, 0, 1, 1), 15)
((1, 0, 2, 0), 16)
((1, 0, 2, 1), 17)
((1, 1, 0, 0), 18)
((1, 1, 0, 1), 19)
((1, 1, 1, 0), 20)
((1, 1, 1, 1), 21)
((1, 1, 2, 0), 22)
((1, 1, 2, 1), 23)


In [34]:
arr = np.arange(24).reshape(3,8)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [37]:
for n in np.ndenumerate(arr):
    print(n)

((0, 0), 0)
((0, 1), 1)
((0, 2), 2)
((0, 3), 3)
((0, 4), 4)
((0, 5), 5)
((0, 6), 6)
((0, 7), 7)
((1, 0), 8)
((1, 1), 9)
((1, 2), 10)
((1, 3), 11)
((1, 4), 12)
((1, 5), 13)
((1, 6), 14)
((1, 7), 15)
((2, 0), 16)
((2, 1), 17)
((2, 2), 18)
((2, 3), 19)
((2, 4), 20)
((2, 5), 21)
((2, 6), 22)
((2, 7), 23)


In [39]:
# operations
arr + arr

array([[ 0,  2,  4,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42, 44, 46]])

In [40]:
arr * arr

array([[  0,   1,   4,   9,  16,  25,  36,  49],
       [ 64,  81, 100, 121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400, 441, 484, 529]])

In [41]:
arr**2

array([[  0,   1,   4,   9,  16,  25,  36,  49],
       [ 64,  81, 100, 121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400, 441, 484, 529]], dtype=int32)

In [42]:
arr*10

array([[  0,  10,  20,  30,  40,  50,  60,  70],
       [ 80,  90, 100, 110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200, 210, 220, 230]])

In [43]:
1 / arr

c:\Miniconda\envs\py37_default\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
        0.2       , 0.16666667, 0.14285714],
       [0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333,
        0.07692308, 0.07142857, 0.06666667],
       [0.0625    , 0.05882353, 0.05555556, 0.05263158, 0.05      ,
        0.04761905, 0.04545455, 0.04347826]])

In [44]:
# .T Returns the transpose of the numpy array
# .T returns self is returned if self.ndim < 2
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr1 = arr.reshape(2,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
arr1.shape

(2, 5)

In [50]:
arr1.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [51]:
arr1.T.shape

(5, 2)

In [54]:
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [55]:
arr.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [56]:
arr.T.shape

(4, 3, 2)

In [63]:
arr = np.arange(24).reshape(2,2,2,3)
arr

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [64]:
arr.T.shape

(3, 2, 2, 2)

In [65]:
arr.T

array([[[[ 0, 12],
         [ 6, 18]],

        [[ 3, 15],
         [ 9, 21]]],


       [[[ 1, 13],
         [ 7, 19]],

        [[ 4, 16],
         [10, 22]]],


       [[[ 2, 14],
         [ 8, 20]],

        [[ 5, 17],
         [11, 23]]]])

In [70]:
# transpose() - This function permutes or reverses the dimension of the given array
# and returns the modified array.
arr =  np.arange(1,7).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr.transpose(0,1)

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
arr.transpose(1,0)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [73]:
arr.shape

(2, 3)

In [74]:
arr.shape[0]

2

In [75]:
arr.shape[1]

3

In [76]:
arr = np.arange(1,21).reshape(2,5,2)
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [77]:
arr.transpose(0,1,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [78]:
arr.transpose(0,1,2).shape

(2, 5, 2)

In [80]:
arr.transpose(1,0,2)

array([[[ 1,  2],
        [11, 12]],

       [[ 3,  4],
        [13, 14]],

       [[ 5,  6],
        [15, 16]],

       [[ 7,  8],
        [17, 18]],

       [[ 9, 10],
        [19, 20]]])

In [81]:
arr.transpose(1,0,2).shape

(5, 2, 2)

In [82]:
arr.shape

(2, 5, 2)

In [83]:
# swap axis
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [88]:
arr.swapaxes(0,1)

array([[[ 1,  2],
        [11, 12]],

       [[ 3,  4],
        [13, 14]],

       [[ 5,  6],
        [15, 16]],

       [[ 7,  8],
        [17, 18]],

       [[ 9, 10],
        [19, 20]]])

In [89]:
arr.swapaxes(0,1).shape

(5, 2, 2)

In [90]:
arr.swapaxes(1,2)

array([[[ 1,  3,  5,  7,  9],
        [ 2,  4,  6,  8, 10]],

       [[11, 13, 15, 17, 19],
        [12, 14, 16, 18, 20]]])

In [91]:
arr.swapaxes(1,2).shape

(2, 2, 5)

In [92]:
arr.shape

(2, 5, 2)

In [93]:
arr_s = arr.swapaxes(1,2)
arr_s

array([[[ 1,  3,  5,  7,  9],
        [ 2,  4,  6,  8, 10]],

       [[11, 13, 15, 17, 19],
        [12, 14, 16, 18, 20]]])

In [94]:
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [95]:
arr_s.base

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [96]:
arr[1] = 100
arr

array([[[  1,   2],
        [  3,   4],
        [  5,   6],
        [  7,   8],
        [  9,  10]],

       [[100, 100],
        [100, 100],
        [100, 100],
        [100, 100],
        [100, 100]]])

In [97]:
arr_s

array([[[  1,   3,   5,   7,   9],
        [  2,   4,   6,   8,  10]],

       [[100, 100, 100, 100, 100],
        [100, 100, 100, 100, 100]]])