# Molly Moran
## Week 11 - 11/4/2025 - 11/6/2025
### Python NumPy Universal Funcitons

In [1]:
import numpy as np


'''
NumPy universal funcitons (unfuncs) are funcitons that operate
on NumPy arrays (ndarrays) in an element-by-element fashion
'''

arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [2]:
# sqrt
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [3]:
# exp()
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [4]:
arr = np.random.randint(10)
arr

8

In [7]:
from numpy.random import randn

In [11]:
arr1 = randn(10).reshape(5,2)
arr1

array([[-1.26562994, -1.11879765],
       [-0.26691896, -1.65191162],
       [-0.06684438, -0.7508264 ],
       [-0.3564999 , -1.04434382],
       [-0.95087429, -1.87088252]])

In [12]:
arr2 = randn(10).reshape(5,2)
arr2

array([[ 0.11606088,  0.25690335],
       [-0.16070543,  0.21352754],
       [-0.17878549,  0.78978434],
       [-0.67575641,  0.56751413],
       [-2.11965585, -0.89345978]])

In [13]:
np.add(arr1,arr2)

array([[-1.14956906, -0.8618943 ],
       [-0.42762439, -1.43838408],
       [-0.24562987,  0.03895794],
       [-1.03225631, -0.47682968],
       [-3.07053015, -2.7643423 ]])

In [14]:
np.maximum(arr1,arr2)

array([[ 0.11606088,  0.25690335],
       [-0.16070543,  0.21352754],
       [-0.06684438,  0.78978434],
       [-0.3564999 ,  0.56751413],
       [-0.95087429, -0.89345978]])

In [15]:
np.minimum(arr1,arr2)

array([[-1.26562994, -1.11879765],
       [-0.26691896, -1.65191162],
       [-0.17878549, -0.7508264 ],
       [-0.67575641, -1.04434382],
       [-2.11965585, -1.87088252]])

In [16]:
# array filtering 
arr = np.arange(1,22).reshape(7,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [17]:
arr>6

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [19]:
arr[arr<=6]

array([1, 2, 3, 4, 5, 6])

In [1]:
import numpy as np
from numpy import random
from numpy.random import randn

In [2]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
arr[arr > 3]

array([4, 5, 6, 7, 8])

In [5]:
arr[:,1]

array([1, 4, 7])

In [6]:
arr[arr[:,1] > 3,1]

array([4, 7])

In [7]:
#Array filtering using where, replace values of an array, 
np.where([True,False,True],1,0)

array([1, 0, 1])

In [9]:
arr = randn(3,3)
arr

array([[ 0.27705758, -0.30276343, -0.96793364],
       [-0.28444404,  0.82874915,  0.084604  ],
       [-0.25487562, -0.9683241 , -3.51040464]])

In [10]:
np.where(arr<0,0,arr)

array([[0.27705758, 0.        , 0.        ],
       [0.        , 0.82874915, 0.084604  ],
       [0.        , 0.        , 0.        ]])

In [11]:
np.where(arr<0,1,arr)

array([[0.27705758, 1.        , 1.        ],
       [1.        , 0.82874915, 0.084604  ],
       [1.        , 1.        , 1.        ]])

In [12]:
sample = [True,False]
arr_b = random.choice(sample,size=5)
arr_b

array([ True, False, False, False, False])

In [13]:
arr1 = np.arange(1,6)
arr2 = arr1 * 5

In [14]:
arr1

array([1, 2, 3, 4, 5])

In [15]:
arr2

array([ 5, 10, 15, 20, 25])

In [16]:
list(zip(arr1,arr2,arr_b))

[(1, 5, True), (2, 10, False), (3, 15, False), (4, 20, False), (5, 25, False)]

In [17]:
arr3 = [v1 if c else v2 for v1,v2,c in zip(arr1,arr2,arr_b)]
arr3

[1, 10, 15, 20, 25]

In [19]:
arr3 = np.where(arr_b,arr1,arr2)
arr3

array([ 1, 10, 15, 20, 25])

In [22]:
# using where with a 2-D array
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)

arr_b = np.array([ random.choice(sample,size=2), random.choice(sample, size=2)])
arr1

array([[1, 2],
       [3, 4]])

In [23]:
arr2

array([[5, 6],
       [7, 8]])

In [24]:
arr_b

array([[False, False],
       [ True,  True]])

In [25]:
arr3 = np.where(arr_b,arr1,arr2)
arr3

array([[5, 6],
       [3, 4]])

In [26]:
# any and all
arr_b.any() # returns true if any of the elements of 'a' evaluate to True.

True

In [27]:
arr_b.all() # Returns true if all elemets evalate to true

False

In [29]:
#unique()
fruits = ['Apple', 'Cherry', 'Orange', 'Banana']
arr = random.choice(fruits, size = 15)
arr

array(['Orange', 'Apple', 'Orange', 'Orange', 'Cherry', 'Cherry',
       'Banana', 'Orange', 'Cherry', 'Cherry', 'Banana', 'Apple',
       'Banana', 'Orange', 'Orange'], dtype='<U6')

In [31]:
np.unique(arr)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [34]:
np.in1d(['Apple', 'Cherry' 'Grape'],arr)

array([ True, False])

In [36]:
# Descrptive statistical Measures
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
np.sum(arr)

45

In [39]:
arr.sum(0)

array([12, 15, 18])

In [41]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [42]:
arr.sum(1)

array([ 6, 15, 24])

In [43]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [44]:
arr.mean()

5.0

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr.mean(0)

array([4., 5., 6.])

In [47]:
arr.mean(1)

array([2., 5., 8.])

In [48]:
np.mean(arr)

5.0

In [49]:
np.mean(arr,axis=1)

array([2., 5., 8.])

In [50]:
np.mean(arr, axis=0)

array([4., 5., 6.])

In [52]:
arr = random.choice(np.arange(5,59),size=20)
arr

array([ 6, 54, 58, 30, 17,  5, 42, 39, 26, 35, 51, 39, 25, 30, 28, 18, 40,
       24, 11, 22])

In [53]:
arr.sort()
arr

array([ 5,  6, 11, 17, 18, 22, 24, 25, 26, 28, 30, 30, 35, 39, 39, 40, 42,
       51, 54, 58])

In [54]:
# joining and splitting NumPy Arrays 
arr1 = np.arange(1,5)
arr2 = np.arange(5,9)

In [55]:
arr1

array([1, 2, 3, 4])

In [56]:
arr2

array([5, 6, 7, 8])

In [59]:
arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
arr1 = arr1.reshape(2,2)
arr2 = arr2.reshape(2,2)


In [61]:
arr1

array([[1, 2],
       [3, 4]])

In [62]:
arr2

array([[5, 6],
       [7, 8]])

In [63]:
arr = np.concatenate((arr1,arr2))
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [66]:
arr = np.concatenate((arr1,arr2),axis=1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [67]:
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

In [69]:
newarr = np.array_split(arr,3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [71]:
newarr[0]

array([1, 2])

In [73]:
newarr = np.array_split(arr,4)
newarr

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [74]:
 # NumPy, the elipsis (...)
# It represnets an arbitary number of dimensions
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr[...]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr = np.arange(1,7).reshape(2,3)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
arr[...]

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
arr[...,-1]

array([3, 6])

In [79]:
arr[...,1]

array([2, 5])

In [80]:
arr = np.arange(1,9).reshape(2,2,2)
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [81]:
arr.shape

(2, 2, 2)

In [82]:
arr[...]

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [83]:
arr[1]

array([[5, 6],
       [7, 8]])

In [84]:
arr[1,...,0]

array([5, 7])

In [87]:
# Example 1 - Sales Trend Analysis:
# Analysis: Calculate the average monthly sales and the percentage chnage
# in sales from the begining to the end of the year.
sales = random.choice(np.arange(100,500), size = 12)
sales

array([155, 175, 475, 248, 422, 333, 249, 222, 189, 110, 497, 389])

In [88]:
average_sales = np.mean(sales)
average_sales

288.6666666666667

In [90]:
percentage_change = ((sales[-1] -sales[0]/sales[0]) * 100)
percentage_change

38800.0

In [93]:
# Example 2: # Exam Scores
# this class is so boring I hate it
scores = random.choice(np.arange(0,101), size = 20)
scores

array([ 3, 32, 57, 24, 39, 88, 63, 19, 39, 96,  2, 62,  1,  4, 87, 32, 70,
       70, 23, 85])

In [94]:
average_scores = np.mean(scores)
average_scores

44.8

In [96]:
# find passing scores > 70
passing_scores = scores[scores >=70]
passing_scores

array([88, 96, 87, 70, 70, 85])

In [97]:
len(passing_scores)

6

In [98]:
len(passing_scores)/len(scores)

0.3

In [99]:
# Find N largest scores
scores.sort()
scores[-5:]

array([70, 85, 87, 88, 96])